// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.util;

import com.katzan.spring.furnituretest.util.SolrServerServiceImpl;
import org.apache.solr.client.solrj.SolrServer;

privileged aspect SolrServerServiceImpl_Roo_JavaBean {
    
    public SolrServer SolrServerServiceImpl.getSolrServer() {
        return this.solrServer;
    }
    
    public void SolrServerServiceImpl.setSolrServer(SolrServer solrServer) {
        this.solrServer = solrServer;
    }
    
    public String SolrServerServiceImpl.getServerURL() {
        return this.serverURL;
    }
    
    public void SolrServerServiceImpl.setServerURL(String serverURL) {
        this.serverURL = serverURL;
    }
    
}
