// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.repository;

import com.katzan.spring.furnituretest.model.FurnitureCategory;
import com.katzan.spring.furnituretest.repository.FurnitureCategoryRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect FurnitureCategoryRepository_Roo_Jpa_Repository {
    
    declare parents: FurnitureCategoryRepository extends JpaRepository<FurnitureCategory, Long>;
    
    declare parents: FurnitureCategoryRepository extends JpaSpecificationExecutor<FurnitureCategory>;
    
    declare @type: FurnitureCategoryRepository: @Repository;
    
}
