// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.repository;

import com.katzan.spring.furnituretest.model.FurnitureNews;
import com.katzan.spring.furnituretest.repository.FurnitureNewsRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect FurnitureNewsRepository_Roo_Jpa_Repository {
    
    declare parents: FurnitureNewsRepository extends JpaRepository<FurnitureNews, Long>;
    
    declare parents: FurnitureNewsRepository extends JpaSpecificationExecutor<FurnitureNews>;
    
    declare @type: FurnitureNewsRepository: @Repository;
    
}
