// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.repository;

import com.katzan.spring.furnituretest.model.FurnitureCollection;
import com.katzan.spring.furnituretest.repository.FurnitureCollectionRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect FurnitureCollectionRepository_Roo_Jpa_Repository {
    
    declare parents: FurnitureCollectionRepository extends JpaRepository<FurnitureCollection, Long>;
    
    declare parents: FurnitureCollectionRepository extends JpaSpecificationExecutor<FurnitureCollection>;
    
    declare @type: FurnitureCollectionRepository: @Repository;
    
}
