// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.repository;

import com.katzan.spring.furnituretest.model.ImageFile;
import com.katzan.spring.furnituretest.repository.ImageFileRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect ImageFileRepository_Roo_Jpa_Repository {
    
    declare parents: ImageFileRepository extends JpaRepository<ImageFile, Long>;
    
    declare parents: ImageFileRepository extends JpaSpecificationExecutor<ImageFile>;
    
    declare @type: ImageFileRepository: @Repository;
    
}
