// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.repository;

import com.katzan.spring.furnituretest.model.ServiceItem;
import com.katzan.spring.furnituretest.repository.ServiceItemRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect ServiceItemRepository_Roo_Jpa_Repository {
    
    declare parents: ServiceItemRepository extends JpaRepository<ServiceItem, Long>;
    
    declare parents: ServiceItemRepository extends JpaSpecificationExecutor<ServiceItem>;
    
    declare @type: ServiceItemRepository: @Repository;
    
}
