// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.repository;

import com.katzan.spring.furnituretest.model.ShopOrderDetail;
import com.katzan.spring.furnituretest.repository.ShopOrderDetailRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect ShopOrderDetailRepository_Roo_Jpa_Repository {
    
    declare parents: ShopOrderDetailRepository extends JpaRepository<ShopOrderDetail, Long>;
    
    declare parents: ShopOrderDetailRepository extends JpaSpecificationExecutor<ShopOrderDetail>;
    
    declare @type: ShopOrderDetailRepository: @Repository;
    
}
