// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.repository;

import com.katzan.spring.furnituretest.model.ShopOrder;
import com.katzan.spring.furnituretest.repository.ShopOrderRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect ShopOrderRepository_Roo_Jpa_Repository {
    
    declare parents: ShopOrderRepository extends JpaRepository<ShopOrder, Long>;
    
    declare parents: ShopOrderRepository extends JpaSpecificationExecutor<ShopOrder>;
    
    declare @type: ShopOrderRepository: @Repository;
    
}
