// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.repository;

import com.katzan.spring.furnituretest.model.UserAccount;
import com.katzan.spring.furnituretest.repository.UserAccountRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect UserAccountRepository_Roo_Jpa_Repository {
    
    declare parents: UserAccountRepository extends JpaRepository<UserAccount, Long>;
    
    declare parents: UserAccountRepository extends JpaSpecificationExecutor<UserAccount>;
    
    declare @type: UserAccountRepository: @Repository;
    
}
