// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.AboutUs;
import com.katzan.spring.furnituretest.model.AboutUsDataOnDemand;
import com.katzan.spring.furnituretest.repository.AboutUsRepository;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AboutUsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AboutUsDataOnDemand: @Component;
    
    private Random AboutUsDataOnDemand.rnd = new SecureRandom();
    
    private List<AboutUs> AboutUsDataOnDemand.data;
    
    @Autowired
    AboutUsRepository AboutUsDataOnDemand.aboutUsRepository;
    
    public AboutUs AboutUsDataOnDemand.getNewTransientAboutUs(int index) {
        AboutUs obj = new AboutUs();
        setDescription(obj, index);
        setName(obj, index);
        setTitle(obj, index);
        return obj;
    }
    
    public void AboutUsDataOnDemand.setDescription(AboutUs obj, int index) {
        String description = "description_" + index;
        if (description.length() > 1500) {
            description = description.substring(0, 1500);
        }
        obj.setDescription(description);
    }
    
    public void AboutUsDataOnDemand.setName(AboutUs obj, int index) {
        String name = "name_" + index;
        if (name.length() > 200) {
            name = name.substring(0, 200);
        }
        obj.setName(name);
    }
    
    public void AboutUsDataOnDemand.setTitle(AboutUs obj, int index) {
        String title = "title_" + index;
        if (title.length() > 200) {
            title = title.substring(0, 200);
        }
        obj.setTitle(title);
    }
    
    public AboutUs AboutUsDataOnDemand.getSpecificAboutUs(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AboutUs obj = data.get(index);
        Long id = obj.getId();
        return aboutUsRepository.findOne(id);
    }
    
    public AboutUs AboutUsDataOnDemand.getRandomAboutUs() {
        init();
        AboutUs obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return aboutUsRepository.findOne(id);
    }
    
    public boolean AboutUsDataOnDemand.modifyAboutUs(AboutUs obj) {
        return false;
    }
    
    public void AboutUsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = aboutUsRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AboutUs' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AboutUs>();
        for (int i = 0; i < 10; i++) {
            AboutUs obj = getNewTransientAboutUs(i);
            try {
                aboutUsRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            aboutUsRepository.flush();
            data.add(obj);
        }
    }
    
}
