// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.AboutUsDataOnDemand;
import com.katzan.spring.furnituretest.model.AboutUsIntegrationTest;
import com.katzan.spring.furnituretest.repository.AboutUsRepository;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AboutUsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AboutUsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AboutUsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AboutUsIntegrationTest: @Transactional;
    
    @Autowired
    private AboutUsDataOnDemand AboutUsIntegrationTest.dod;
    
    @Autowired
    AboutUsRepository AboutUsIntegrationTest.aboutUsRepository;
    
    @Test
    public void AboutUsIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'AboutUs' failed to initialize correctly", dod.getRandomAboutUs());
        long count = aboutUsRepository.count();
        Assert.assertTrue("Counter for 'AboutUs' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AboutUsIntegrationTest.testFind() {
        AboutUs obj = dod.getRandomAboutUs();
        Assert.assertNotNull("Data on demand for 'AboutUs' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AboutUs' failed to provide an identifier", id);
        obj = aboutUsRepository.findOne(id);
        Assert.assertNotNull("Find method for 'AboutUs' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AboutUs' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AboutUsIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'AboutUs' failed to initialize correctly", dod.getRandomAboutUs());
        long count = aboutUsRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'AboutUs', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AboutUs> result = aboutUsRepository.findAll();
        Assert.assertNotNull("Find all method for 'AboutUs' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AboutUs' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AboutUsIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'AboutUs' failed to initialize correctly", dod.getRandomAboutUs());
        long count = aboutUsRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AboutUs> result = aboutUsRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'AboutUs' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AboutUs' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AboutUsIntegrationTest.testFlush() {
        AboutUs obj = dod.getRandomAboutUs();
        Assert.assertNotNull("Data on demand for 'AboutUs' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AboutUs' failed to provide an identifier", id);
        obj = aboutUsRepository.findOne(id);
        Assert.assertNotNull("Find method for 'AboutUs' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAboutUs(obj);
        Integer currentVersion = obj.getVersion();
        aboutUsRepository.flush();
        Assert.assertTrue("Version for 'AboutUs' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AboutUsIntegrationTest.testSaveUpdate() {
        AboutUs obj = dod.getRandomAboutUs();
        Assert.assertNotNull("Data on demand for 'AboutUs' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AboutUs' failed to provide an identifier", id);
        obj = aboutUsRepository.findOne(id);
        boolean modified =  dod.modifyAboutUs(obj);
        Integer currentVersion = obj.getVersion();
        AboutUs merged = aboutUsRepository.save(obj);
        aboutUsRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AboutUs' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AboutUsIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'AboutUs' failed to initialize correctly", dod.getRandomAboutUs());
        AboutUs obj = dod.getNewTransientAboutUs(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AboutUs' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AboutUs' identifier to be null", obj.getId());
        aboutUsRepository.save(obj);
        aboutUsRepository.flush();
        Assert.assertNotNull("Expected 'AboutUs' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AboutUsIntegrationTest.testDelete() {
        AboutUs obj = dod.getRandomAboutUs();
        Assert.assertNotNull("Data on demand for 'AboutUs' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AboutUs' failed to provide an identifier", id);
        obj = aboutUsRepository.findOne(id);
        aboutUsRepository.delete(obj);
        aboutUsRepository.flush();
        Assert.assertNull("Failed to remove 'AboutUs' with identifier '" + id + "'", aboutUsRepository.findOne(id));
    }
    
}
