// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.BigDataOnDemand;
import com.katzan.spring.furnituretest.model.BigIntegrationTest;
import com.katzan.spring.furnituretest.repository.BigRepository;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BigIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BigIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BigIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BigIntegrationTest: @Transactional;
    
    @Autowired
    BigDataOnDemand BigIntegrationTest.dod;
    
    @Autowired
    BigRepository BigIntegrationTest.bigRepository;
    
    @Test
    public void BigIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Big' failed to initialize correctly", dod.getRandomBig());
        long count = bigRepository.count();
        Assert.assertTrue("Counter for 'Big' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BigIntegrationTest.testFind() {
        Big obj = dod.getRandomBig();
        Assert.assertNotNull("Data on demand for 'Big' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Big' failed to provide an identifier", id);
        obj = bigRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Big' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Big' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BigIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Big' failed to initialize correctly", dod.getRandomBig());
        long count = bigRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Big', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Big> result = bigRepository.findAll();
        Assert.assertNotNull("Find all method for 'Big' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Big' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BigIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Big' failed to initialize correctly", dod.getRandomBig());
        long count = bigRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Big> result = bigRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Big' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Big' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BigIntegrationTest.testFlush() {
        Big obj = dod.getRandomBig();
        Assert.assertNotNull("Data on demand for 'Big' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Big' failed to provide an identifier", id);
        obj = bigRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Big' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBig(obj);
        Integer currentVersion = obj.getVersion();
        bigRepository.flush();
        Assert.assertTrue("Version for 'Big' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BigIntegrationTest.testSaveUpdate() {
        Big obj = dod.getRandomBig();
        Assert.assertNotNull("Data on demand for 'Big' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Big' failed to provide an identifier", id);
        obj = bigRepository.findOne(id);
        boolean modified =  dod.modifyBig(obj);
        Integer currentVersion = obj.getVersion();
        Big merged = bigRepository.save(obj);
        bigRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Big' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BigIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Big' failed to initialize correctly", dod.getRandomBig());
        Big obj = dod.getNewTransientBig(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Big' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Big' identifier to be null", obj.getId());
        bigRepository.save(obj);
        bigRepository.flush();
        Assert.assertNotNull("Expected 'Big' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BigIntegrationTest.testDelete() {
        Big obj = dod.getRandomBig();
        Assert.assertNotNull("Data on demand for 'Big' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Big' failed to provide an identifier", id);
        obj = bigRepository.findOne(id);
        bigRepository.delete(obj);
        bigRepository.flush();
        Assert.assertNull("Failed to remove 'Big' with identifier '" + id + "'", bigRepository.findOne(id));
    }
    
}
