// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.ContactDataOnDemand;
import com.katzan.spring.furnituretest.model.ContactIntegrationTest;
import com.katzan.spring.furnituretest.repository.ContactRepository;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ContactIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ContactIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ContactIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ContactIntegrationTest: @Transactional;
    
    @Autowired
    ContactDataOnDemand ContactIntegrationTest.dod;
    
    @Autowired
    ContactRepository ContactIntegrationTest.contactRepository;
    
    @Test
    public void ContactIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Contact' failed to initialize correctly", dod.getRandomContact());
        long count = contactRepository.count();
        Assert.assertTrue("Counter for 'Contact' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ContactIntegrationTest.testFind() {
        Contact obj = dod.getRandomContact();
        Assert.assertNotNull("Data on demand for 'Contact' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Contact' failed to provide an identifier", id);
        obj = contactRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Contact' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Contact' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ContactIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Contact' failed to initialize correctly", dod.getRandomContact());
        long count = contactRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Contact', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Contact> result = contactRepository.findAll();
        Assert.assertNotNull("Find all method for 'Contact' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Contact' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ContactIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Contact' failed to initialize correctly", dod.getRandomContact());
        long count = contactRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Contact> result = contactRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Contact' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Contact' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ContactIntegrationTest.testFlush() {
        Contact obj = dod.getRandomContact();
        Assert.assertNotNull("Data on demand for 'Contact' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Contact' failed to provide an identifier", id);
        obj = contactRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Contact' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyContact(obj);
        Integer currentVersion = obj.getVersion();
        contactRepository.flush();
        Assert.assertTrue("Version for 'Contact' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContactIntegrationTest.testSaveUpdate() {
        Contact obj = dod.getRandomContact();
        Assert.assertNotNull("Data on demand for 'Contact' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Contact' failed to provide an identifier", id);
        obj = contactRepository.findOne(id);
        boolean modified =  dod.modifyContact(obj);
        Integer currentVersion = obj.getVersion();
        Contact merged = contactRepository.save(obj);
        contactRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Contact' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContactIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Contact' failed to initialize correctly", dod.getRandomContact());
        Contact obj = dod.getNewTransientContact(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Contact' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Contact' identifier to be null", obj.getId());
        contactRepository.save(obj);
        contactRepository.flush();
        Assert.assertNotNull("Expected 'Contact' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ContactIntegrationTest.testDelete() {
        Contact obj = dod.getRandomContact();
        Assert.assertNotNull("Data on demand for 'Contact' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Contact' failed to provide an identifier", id);
        obj = contactRepository.findOne(id);
        contactRepository.delete(obj);
        contactRepository.flush();
        Assert.assertNull("Failed to remove 'Contact' with identifier '" + id + "'", contactRepository.findOne(id));
    }
    
}
