// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.FurnitureNewsIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FurnitureNewsIntegrationTest_Roo_Configurable {
    
    declare @type: FurnitureNewsIntegrationTest: @Configurable;
    
}
