// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.FurnitureCategoryDataOnDemand;
import com.katzan.spring.furnituretest.model.FurnitureCategoryIntegrationTest;
import com.katzan.spring.furnituretest.repository.FurnitureCategoryRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FurnitureCategoryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FurnitureCategoryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FurnitureCategoryIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FurnitureCategoryIntegrationTest: @Transactional;
    
    @Autowired
    FurnitureCategoryDataOnDemand FurnitureCategoryIntegrationTest.dod;
    
    @Autowired
    FurnitureCategoryRepository FurnitureCategoryIntegrationTest.furnitureCategoryRepository;
    
    @Test
    public void FurnitureCategoryIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'FurnitureCategory' failed to initialize correctly", dod.getRandomFurnitureCategory());
        long count = furnitureCategoryRepository.count();
        Assert.assertTrue("Counter for 'FurnitureCategory' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FurnitureCategoryIntegrationTest.testFind() {
        FurnitureCategory obj = dod.getRandomFurnitureCategory();
        Assert.assertNotNull("Data on demand for 'FurnitureCategory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FurnitureCategory' failed to provide an identifier", id);
        obj = furnitureCategoryRepository.findOne(id);
        Assert.assertNotNull("Find method for 'FurnitureCategory' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FurnitureCategory' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FurnitureCategoryIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'FurnitureCategory' failed to initialize correctly", dod.getRandomFurnitureCategory());
        long count = furnitureCategoryRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'FurnitureCategory', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FurnitureCategory> result = furnitureCategoryRepository.findAll();
        Assert.assertNotNull("Find all method for 'FurnitureCategory' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FurnitureCategory' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FurnitureCategoryIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'FurnitureCategory' failed to initialize correctly", dod.getRandomFurnitureCategory());
        long count = furnitureCategoryRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FurnitureCategory> result = furnitureCategoryRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'FurnitureCategory' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FurnitureCategory' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FurnitureCategoryIntegrationTest.testFlush() {
        FurnitureCategory obj = dod.getRandomFurnitureCategory();
        Assert.assertNotNull("Data on demand for 'FurnitureCategory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FurnitureCategory' failed to provide an identifier", id);
        obj = furnitureCategoryRepository.findOne(id);
        Assert.assertNotNull("Find method for 'FurnitureCategory' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFurnitureCategory(obj);
        Integer currentVersion = obj.getVersion();
        furnitureCategoryRepository.flush();
        Assert.assertTrue("Version for 'FurnitureCategory' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FurnitureCategoryIntegrationTest.testSaveUpdate() {
        FurnitureCategory obj = dod.getRandomFurnitureCategory();
        Assert.assertNotNull("Data on demand for 'FurnitureCategory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FurnitureCategory' failed to provide an identifier", id);
        obj = furnitureCategoryRepository.findOne(id);
        boolean modified =  dod.modifyFurnitureCategory(obj);
        Integer currentVersion = obj.getVersion();
        FurnitureCategory merged = furnitureCategoryRepository.save(obj);
        furnitureCategoryRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FurnitureCategory' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FurnitureCategoryIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'FurnitureCategory' failed to initialize correctly", dod.getRandomFurnitureCategory());
        FurnitureCategory obj = dod.getNewTransientFurnitureCategory(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FurnitureCategory' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FurnitureCategory' identifier to be null", obj.getId());
        try {
            furnitureCategoryRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        furnitureCategoryRepository.flush();
        Assert.assertNotNull("Expected 'FurnitureCategory' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FurnitureCategoryIntegrationTest.testDelete() {
        FurnitureCategory obj = dod.getRandomFurnitureCategory();
        Assert.assertNotNull("Data on demand for 'FurnitureCategory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FurnitureCategory' failed to provide an identifier", id);
        obj = furnitureCategoryRepository.findOne(id);
        furnitureCategoryRepository.delete(obj);
        furnitureCategoryRepository.flush();
        Assert.assertNull("Failed to remove 'FurnitureCategory' with identifier '" + id + "'", furnitureCategoryRepository.findOne(id));
    }
    
}
