// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.FurnitureCollectionDataOnDemand;
import com.katzan.spring.furnituretest.model.FurnitureCollectionIntegrationTest;
import com.katzan.spring.furnituretest.repository.FurnitureCollectionRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FurnitureCollectionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FurnitureCollectionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FurnitureCollectionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FurnitureCollectionIntegrationTest: @Transactional;
    
    @Autowired
    FurnitureCollectionDataOnDemand FurnitureCollectionIntegrationTest.dod;
    
    @Autowired
    FurnitureCollectionRepository FurnitureCollectionIntegrationTest.furnitureCollectionRepository;
    
    @Test
    public void FurnitureCollectionIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'FurnitureCollection' failed to initialize correctly", dod.getRandomFurnitureCollection());
        long count = furnitureCollectionRepository.count();
        Assert.assertTrue("Counter for 'FurnitureCollection' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FurnitureCollectionIntegrationTest.testFind() {
        FurnitureCollection obj = dod.getRandomFurnitureCollection();
        Assert.assertNotNull("Data on demand for 'FurnitureCollection' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FurnitureCollection' failed to provide an identifier", id);
        obj = furnitureCollectionRepository.findOne(id);
        Assert.assertNotNull("Find method for 'FurnitureCollection' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FurnitureCollection' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FurnitureCollectionIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'FurnitureCollection' failed to initialize correctly", dod.getRandomFurnitureCollection());
        long count = furnitureCollectionRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'FurnitureCollection', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FurnitureCollection> result = furnitureCollectionRepository.findAll();
        Assert.assertNotNull("Find all method for 'FurnitureCollection' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FurnitureCollection' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FurnitureCollectionIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'FurnitureCollection' failed to initialize correctly", dod.getRandomFurnitureCollection());
        long count = furnitureCollectionRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FurnitureCollection> result = furnitureCollectionRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'FurnitureCollection' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FurnitureCollection' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FurnitureCollectionIntegrationTest.testFlush() {
        FurnitureCollection obj = dod.getRandomFurnitureCollection();
        Assert.assertNotNull("Data on demand for 'FurnitureCollection' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FurnitureCollection' failed to provide an identifier", id);
        obj = furnitureCollectionRepository.findOne(id);
        Assert.assertNotNull("Find method for 'FurnitureCollection' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFurnitureCollection(obj);
        Integer currentVersion = obj.getVersion();
        furnitureCollectionRepository.flush();
        Assert.assertTrue("Version for 'FurnitureCollection' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FurnitureCollectionIntegrationTest.testSaveUpdate() {
        FurnitureCollection obj = dod.getRandomFurnitureCollection();
        Assert.assertNotNull("Data on demand for 'FurnitureCollection' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FurnitureCollection' failed to provide an identifier", id);
        obj = furnitureCollectionRepository.findOne(id);
        boolean modified =  dod.modifyFurnitureCollection(obj);
        Integer currentVersion = obj.getVersion();
        FurnitureCollection merged = furnitureCollectionRepository.save(obj);
        furnitureCollectionRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FurnitureCollection' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FurnitureCollectionIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'FurnitureCollection' failed to initialize correctly", dod.getRandomFurnitureCollection());
        FurnitureCollection obj = dod.getNewTransientFurnitureCollection(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FurnitureCollection' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FurnitureCollection' identifier to be null", obj.getId());
        try {
            furnitureCollectionRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        furnitureCollectionRepository.flush();
        Assert.assertNotNull("Expected 'FurnitureCollection' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FurnitureCollectionIntegrationTest.testDelete() {
        FurnitureCollection obj = dod.getRandomFurnitureCollection();
        Assert.assertNotNull("Data on demand for 'FurnitureCollection' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FurnitureCollection' failed to provide an identifier", id);
        obj = furnitureCollectionRepository.findOne(id);
        furnitureCollectionRepository.delete(obj);
        furnitureCollectionRepository.flush();
        Assert.assertNull("Failed to remove 'FurnitureCollection' with identifier '" + id + "'", furnitureCollectionRepository.findOne(id));
    }
    
}
