// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.FurnitureNewsDataOnDemand;
import com.katzan.spring.furnituretest.model.FurnitureNewsIntegrationTest;
import com.katzan.spring.furnituretest.repository.FurnitureNewsRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FurnitureNewsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FurnitureNewsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FurnitureNewsIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FurnitureNewsIntegrationTest: @Transactional;
    
    @Autowired
    FurnitureNewsDataOnDemand FurnitureNewsIntegrationTest.dod;
    
    @Autowired
    FurnitureNewsRepository FurnitureNewsIntegrationTest.furnitureNewsRepository;
    
    @Test
    public void FurnitureNewsIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'FurnitureNews' failed to initialize correctly", dod.getRandomFurnitureNews());
        long count = furnitureNewsRepository.count();
        Assert.assertTrue("Counter for 'FurnitureNews' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FurnitureNewsIntegrationTest.testFind() {
        FurnitureNews obj = dod.getRandomFurnitureNews();
        Assert.assertNotNull("Data on demand for 'FurnitureNews' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FurnitureNews' failed to provide an identifier", id);
        obj = furnitureNewsRepository.findOne(id);
        Assert.assertNotNull("Find method for 'FurnitureNews' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FurnitureNews' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FurnitureNewsIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'FurnitureNews' failed to initialize correctly", dod.getRandomFurnitureNews());
        long count = furnitureNewsRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'FurnitureNews', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FurnitureNews> result = furnitureNewsRepository.findAll();
        Assert.assertNotNull("Find all method for 'FurnitureNews' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FurnitureNews' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FurnitureNewsIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'FurnitureNews' failed to initialize correctly", dod.getRandomFurnitureNews());
        long count = furnitureNewsRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FurnitureNews> result = furnitureNewsRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'FurnitureNews' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FurnitureNews' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FurnitureNewsIntegrationTest.testFlush() {
        FurnitureNews obj = dod.getRandomFurnitureNews();
        Assert.assertNotNull("Data on demand for 'FurnitureNews' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FurnitureNews' failed to provide an identifier", id);
        obj = furnitureNewsRepository.findOne(id);
        Assert.assertNotNull("Find method for 'FurnitureNews' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFurnitureNews(obj);
        Integer currentVersion = obj.getVersion();
        furnitureNewsRepository.flush();
        Assert.assertTrue("Version for 'FurnitureNews' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FurnitureNewsIntegrationTest.testSaveUpdate() {
        FurnitureNews obj = dod.getRandomFurnitureNews();
        Assert.assertNotNull("Data on demand for 'FurnitureNews' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FurnitureNews' failed to provide an identifier", id);
        obj = furnitureNewsRepository.findOne(id);
        boolean modified =  dod.modifyFurnitureNews(obj);
        Integer currentVersion = obj.getVersion();
        FurnitureNews merged = furnitureNewsRepository.save(obj);
        furnitureNewsRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FurnitureNews' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FurnitureNewsIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'FurnitureNews' failed to initialize correctly", dod.getRandomFurnitureNews());
        FurnitureNews obj = dod.getNewTransientFurnitureNews(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FurnitureNews' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FurnitureNews' identifier to be null", obj.getId());
        try {
            furnitureNewsRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        furnitureNewsRepository.flush();
        Assert.assertNotNull("Expected 'FurnitureNews' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FurnitureNewsIntegrationTest.testDelete() {
        FurnitureNews obj = dod.getRandomFurnitureNews();
        Assert.assertNotNull("Data on demand for 'FurnitureNews' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FurnitureNews' failed to provide an identifier", id);
        obj = furnitureNewsRepository.findOne(id);
        furnitureNewsRepository.delete(obj);
        furnitureNewsRepository.flush();
        Assert.assertNull("Failed to remove 'FurnitureNews' with identifier '" + id + "'", furnitureNewsRepository.findOne(id));
    }
    
}
