// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.FurnitureItemDataOnDemand;
import com.katzan.spring.furnituretest.model.FurnitureItemIntegrationTest;
import com.katzan.spring.furnituretest.repository.FurnitureItemRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FurnitureItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FurnitureItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FurnitureItemIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FurnitureItemIntegrationTest: @Transactional;
    
    @Autowired
    FurnitureItemDataOnDemand FurnitureItemIntegrationTest.dod;
    
    @Autowired
    FurnitureItemRepository FurnitureItemIntegrationTest.furnitureItemRepository;
    
    @Test
    public void FurnitureItemIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'FurnitureItem' failed to initialize correctly", dod.getRandomFurnitureItem());
        long count = furnitureItemRepository.count();
        Assert.assertTrue("Counter for 'FurnitureItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FurnitureItemIntegrationTest.testFind() {
        FurnitureItem obj = dod.getRandomFurnitureItem();
        Assert.assertNotNull("Data on demand for 'FurnitureItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FurnitureItem' failed to provide an identifier", id);
        obj = furnitureItemRepository.findOne(id);
        Assert.assertNotNull("Find method for 'FurnitureItem' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FurnitureItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FurnitureItemIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'FurnitureItem' failed to initialize correctly", dod.getRandomFurnitureItem());
        long count = furnitureItemRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'FurnitureItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FurnitureItem> result = furnitureItemRepository.findAll();
        Assert.assertNotNull("Find all method for 'FurnitureItem' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FurnitureItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FurnitureItemIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'FurnitureItem' failed to initialize correctly", dod.getRandomFurnitureItem());
        long count = furnitureItemRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FurnitureItem> result = furnitureItemRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'FurnitureItem' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FurnitureItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FurnitureItemIntegrationTest.testFlush() {
        FurnitureItem obj = dod.getRandomFurnitureItem();
        Assert.assertNotNull("Data on demand for 'FurnitureItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FurnitureItem' failed to provide an identifier", id);
        obj = furnitureItemRepository.findOne(id);
        Assert.assertNotNull("Find method for 'FurnitureItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFurnitureItem(obj);
        Integer currentVersion = obj.getVersion();
        furnitureItemRepository.flush();
        Assert.assertTrue("Version for 'FurnitureItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FurnitureItemIntegrationTest.testSaveUpdate() {
        FurnitureItem obj = dod.getRandomFurnitureItem();
        Assert.assertNotNull("Data on demand for 'FurnitureItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FurnitureItem' failed to provide an identifier", id);
        obj = furnitureItemRepository.findOne(id);
        boolean modified =  dod.modifyFurnitureItem(obj);
        Integer currentVersion = obj.getVersion();
        FurnitureItem merged = furnitureItemRepository.save(obj);
        furnitureItemRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FurnitureItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FurnitureItemIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'FurnitureItem' failed to initialize correctly", dod.getRandomFurnitureItem());
        FurnitureItem obj = dod.getNewTransientFurnitureItem(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FurnitureItem' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FurnitureItem' identifier to be null", obj.getId());
        try {
            furnitureItemRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        furnitureItemRepository.flush();
        Assert.assertNotNull("Expected 'FurnitureItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FurnitureItemIntegrationTest.testDelete() {
        FurnitureItem obj = dod.getRandomFurnitureItem();
        Assert.assertNotNull("Data on demand for 'FurnitureItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FurnitureItem' failed to provide an identifier", id);
        obj = furnitureItemRepository.findOne(id);
        furnitureItemRepository.delete(obj);
        furnitureItemRepository.flush();
        Assert.assertNull("Failed to remove 'FurnitureItem' with identifier '" + id + "'", furnitureItemRepository.findOne(id));
    }
    
}
