// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.ServiceItemDataOnDemand;
import com.katzan.spring.furnituretest.model.ServiceItemIntegrationTest;
import com.katzan.spring.furnituretest.repository.ServiceItemRepository;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ServiceItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ServiceItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ServiceItemIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ServiceItemIntegrationTest: @Transactional;
    
    @Autowired
    private ServiceItemDataOnDemand ServiceItemIntegrationTest.dod;
    
    @Autowired
    ServiceItemRepository ServiceItemIntegrationTest.serviceItemRepository;
    
    @Test
    public void ServiceItemIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'ServiceItem' failed to initialize correctly", dod.getRandomServiceItem());
        long count = serviceItemRepository.count();
        Assert.assertTrue("Counter for 'ServiceItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ServiceItemIntegrationTest.testFind() {
        ServiceItem obj = dod.getRandomServiceItem();
        Assert.assertNotNull("Data on demand for 'ServiceItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServiceItem' failed to provide an identifier", id);
        obj = serviceItemRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ServiceItem' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ServiceItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ServiceItemIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'ServiceItem' failed to initialize correctly", dod.getRandomServiceItem());
        long count = serviceItemRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'ServiceItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ServiceItem> result = serviceItemRepository.findAll();
        Assert.assertNotNull("Find all method for 'ServiceItem' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ServiceItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ServiceItemIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'ServiceItem' failed to initialize correctly", dod.getRandomServiceItem());
        long count = serviceItemRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ServiceItem> result = serviceItemRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'ServiceItem' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ServiceItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ServiceItemIntegrationTest.testFlush() {
        ServiceItem obj = dod.getRandomServiceItem();
        Assert.assertNotNull("Data on demand for 'ServiceItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServiceItem' failed to provide an identifier", id);
        obj = serviceItemRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ServiceItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyServiceItem(obj);
        Integer currentVersion = obj.getVersion();
        serviceItemRepository.flush();
        Assert.assertTrue("Version for 'ServiceItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ServiceItemIntegrationTest.testSaveUpdate() {
        ServiceItem obj = dod.getRandomServiceItem();
        Assert.assertNotNull("Data on demand for 'ServiceItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServiceItem' failed to provide an identifier", id);
        obj = serviceItemRepository.findOne(id);
        boolean modified =  dod.modifyServiceItem(obj);
        Integer currentVersion = obj.getVersion();
        ServiceItem merged = serviceItemRepository.save(obj);
        serviceItemRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ServiceItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ServiceItemIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'ServiceItem' failed to initialize correctly", dod.getRandomServiceItem());
        ServiceItem obj = dod.getNewTransientServiceItem(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ServiceItem' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ServiceItem' identifier to be null", obj.getId());
        serviceItemRepository.save(obj);
        serviceItemRepository.flush();
        Assert.assertNotNull("Expected 'ServiceItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ServiceItemIntegrationTest.testDelete() {
        ServiceItem obj = dod.getRandomServiceItem();
        Assert.assertNotNull("Data on demand for 'ServiceItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServiceItem' failed to provide an identifier", id);
        obj = serviceItemRepository.findOne(id);
        serviceItemRepository.delete(obj);
        serviceItemRepository.flush();
        Assert.assertNull("Failed to remove 'ServiceItem' with identifier '" + id + "'", serviceItemRepository.findOne(id));
    }
    
}
