// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.ShopOrderDataOnDemand;
import com.katzan.spring.furnituretest.model.ShopOrderIntegrationTest;
import com.katzan.spring.furnituretest.repository.ShopOrderRepository;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ShopOrderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ShopOrderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ShopOrderIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ShopOrderIntegrationTest: @Transactional;
    
    @Autowired
    ShopOrderDataOnDemand ShopOrderIntegrationTest.dod;
    
    @Autowired
    ShopOrderRepository ShopOrderIntegrationTest.shopOrderRepository;
    
    @Test
    public void ShopOrderIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'ShopOrder' failed to initialize correctly", dod.getRandomShopOrder());
        long count = shopOrderRepository.count();
        Assert.assertTrue("Counter for 'ShopOrder' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ShopOrderIntegrationTest.testFind() {
        ShopOrder obj = dod.getRandomShopOrder();
        Assert.assertNotNull("Data on demand for 'ShopOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ShopOrder' failed to provide an identifier", id);
        obj = shopOrderRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ShopOrder' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ShopOrder' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ShopOrderIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'ShopOrder' failed to initialize correctly", dod.getRandomShopOrder());
        long count = shopOrderRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'ShopOrder', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ShopOrder> result = shopOrderRepository.findAll();
        Assert.assertNotNull("Find all method for 'ShopOrder' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ShopOrder' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ShopOrderIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'ShopOrder' failed to initialize correctly", dod.getRandomShopOrder());
        long count = shopOrderRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ShopOrder> result = shopOrderRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'ShopOrder' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ShopOrder' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ShopOrderIntegrationTest.testFlush() {
        ShopOrder obj = dod.getRandomShopOrder();
        Assert.assertNotNull("Data on demand for 'ShopOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ShopOrder' failed to provide an identifier", id);
        obj = shopOrderRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ShopOrder' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyShopOrder(obj);
        Integer currentVersion = obj.getVersion();
        shopOrderRepository.flush();
        Assert.assertTrue("Version for 'ShopOrder' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ShopOrderIntegrationTest.testSaveUpdate() {
        ShopOrder obj = dod.getRandomShopOrder();
        Assert.assertNotNull("Data on demand for 'ShopOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ShopOrder' failed to provide an identifier", id);
        obj = shopOrderRepository.findOne(id);
        boolean modified =  dod.modifyShopOrder(obj);
        Integer currentVersion = obj.getVersion();
        ShopOrder merged = shopOrderRepository.save(obj);
        shopOrderRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ShopOrder' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ShopOrderIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'ShopOrder' failed to initialize correctly", dod.getRandomShopOrder());
        ShopOrder obj = dod.getNewTransientShopOrder(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ShopOrder' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ShopOrder' identifier to be null", obj.getId());
        shopOrderRepository.save(obj);
        shopOrderRepository.flush();
        Assert.assertNotNull("Expected 'ShopOrder' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ShopOrderIntegrationTest.testDelete() {
        ShopOrder obj = dod.getRandomShopOrder();
        Assert.assertNotNull("Data on demand for 'ShopOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ShopOrder' failed to provide an identifier", id);
        obj = shopOrderRepository.findOne(id);
        shopOrderRepository.delete(obj);
        shopOrderRepository.flush();
        Assert.assertNull("Failed to remove 'ShopOrder' with identifier '" + id + "'", shopOrderRepository.findOne(id));
    }
    
}
