// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.FurnitureItemDataOnDemand;
import com.katzan.spring.furnituretest.model.ShopOrderDetail;
import com.katzan.spring.furnituretest.model.ShopOrderDetailDataOnDemand;
import com.katzan.spring.furnituretest.repository.ShopOrderDetailRepository;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ShopOrderDetailDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ShopOrderDetailDataOnDemand: @Component;
    
    private Random ShopOrderDetailDataOnDemand.rnd = new SecureRandom();
    
    private List<ShopOrderDetail> ShopOrderDetailDataOnDemand.data;
    
    @Autowired
    FurnitureItemDataOnDemand ShopOrderDetailDataOnDemand.furnitureItemDataOnDemand;
    
    @Autowired
    ShopOrderDetailRepository ShopOrderDetailDataOnDemand.shopOrderDetailRepository;
    
    public ShopOrderDetail ShopOrderDetailDataOnDemand.getNewTransientShopOrderDetail(int index) {
        ShopOrderDetail obj = new ShopOrderDetail();
        setQuantity(obj, index);
        return obj;
    }
    
    public void ShopOrderDetailDataOnDemand.setQuantity(ShopOrderDetail obj, int index) {
        Integer quantity = new Integer(index);
        obj.setQuantity(quantity);
    }
    
    public ShopOrderDetail ShopOrderDetailDataOnDemand.getSpecificShopOrderDetail(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ShopOrderDetail obj = data.get(index);
        Long id = obj.getId();
        return shopOrderDetailRepository.findOne(id);
    }
    
    public ShopOrderDetail ShopOrderDetailDataOnDemand.getRandomShopOrderDetail() {
        init();
        ShopOrderDetail obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return shopOrderDetailRepository.findOne(id);
    }
    
    public boolean ShopOrderDetailDataOnDemand.modifyShopOrderDetail(ShopOrderDetail obj) {
        return false;
    }
    
    public void ShopOrderDetailDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = shopOrderDetailRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ShopOrderDetail' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ShopOrderDetail>();
        for (int i = 0; i < 10; i++) {
            ShopOrderDetail obj = getNewTransientShopOrderDetail(i);
            try {
                shopOrderDetailRepository.save(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            shopOrderDetailRepository.flush();
            data.add(obj);
        }
    }
    
}
