// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.web;

import com.katzan.spring.furnituretest.model.AboutUs;
import com.katzan.spring.furnituretest.model.Article;
import com.katzan.spring.furnituretest.model.Big;
import com.katzan.spring.furnituretest.model.Contact;
import com.katzan.spring.furnituretest.model.FurnitureCategory;
import com.katzan.spring.furnituretest.model.FurnitureCollection;
import com.katzan.spring.furnituretest.model.FurnitureItem;
import com.katzan.spring.furnituretest.model.FurnitureNews;
import com.katzan.spring.furnituretest.model.ImageFile;
import com.katzan.spring.furnituretest.model.ServiceItem;
import com.katzan.spring.furnituretest.model.ShopOrder;
import com.katzan.spring.furnituretest.model.ShopOrderDetail;
import com.katzan.spring.furnituretest.repository.AboutUsRepository;
import com.katzan.spring.furnituretest.repository.ArticleRepository;
import com.katzan.spring.furnituretest.repository.BigRepository;
import com.katzan.spring.furnituretest.repository.ContactRepository;
import com.katzan.spring.furnituretest.repository.FurnitureCategoryRepository;
import com.katzan.spring.furnituretest.repository.FurnitureCollectionRepository;
import com.katzan.spring.furnituretest.repository.FurnitureItemRepository;
import com.katzan.spring.furnituretest.repository.FurnitureNewsRepository;
import com.katzan.spring.furnituretest.repository.ImageFileRepository;
import com.katzan.spring.furnituretest.repository.ServiceItemRepository;
import com.katzan.spring.furnituretest.repository.ShopOrderRepository;
import com.katzan.spring.furnituretest.web.ApplicationConversionServiceFactoryBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.core.convert.converter.Converter;
import org.springframework.format.FormatterRegistry;

privileged aspect ApplicationConversionServiceFactoryBean_Roo_ConversionService {
    
    declare @type: ApplicationConversionServiceFactoryBean: @Configurable;
    
    @Autowired
    AboutUsRepository ApplicationConversionServiceFactoryBean.aboutUsRepository;
    
    @Autowired
    ArticleRepository ApplicationConversionServiceFactoryBean.articleRepository;
    
    @Autowired
    BigRepository ApplicationConversionServiceFactoryBean.bigRepository;
    
    @Autowired
    ContactRepository ApplicationConversionServiceFactoryBean.contactRepository;
    
    @Autowired
    FurnitureCategoryRepository ApplicationConversionServiceFactoryBean.furnitureCategoryRepository;
    
    @Autowired
    FurnitureCollectionRepository ApplicationConversionServiceFactoryBean.furnitureCollectionRepository;
    
    @Autowired
    FurnitureItemRepository ApplicationConversionServiceFactoryBean.furnitureItemRepository;
    
    @Autowired
    FurnitureNewsRepository ApplicationConversionServiceFactoryBean.furnitureNewsRepository;
    
    @Autowired
    ImageFileRepository ApplicationConversionServiceFactoryBean.imageFileRepository;
    
    @Autowired
    ServiceItemRepository ApplicationConversionServiceFactoryBean.serviceItemRepository;
    
    @Autowired
    ShopOrderRepository ApplicationConversionServiceFactoryBean.shopOrderRepository;
    
    public Converter<AboutUs, String> ApplicationConversionServiceFactoryBean.getAboutUsToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.katzan.spring.furnituretest.model.AboutUs, java.lang.String>() {
            public String convert(AboutUs aboutUs) {
                return new StringBuilder().append(aboutUs.getName()).append(' ').append(aboutUs.getTitle()).append(' ').append(aboutUs.getDescription()).toString();
            }
        };
    }
    
    public Converter<Long, AboutUs> ApplicationConversionServiceFactoryBean.getIdToAboutUsConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.katzan.spring.furnituretest.model.AboutUs>() {
            public com.katzan.spring.furnituretest.model.AboutUs convert(java.lang.Long id) {
                return aboutUsRepository.findOne(id);
            }
        };
    }
    
    public Converter<String, AboutUs> ApplicationConversionServiceFactoryBean.getStringToAboutUsConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.katzan.spring.furnituretest.model.AboutUs>() {
            public com.katzan.spring.furnituretest.model.AboutUs convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), AboutUs.class);
            }
        };
    }
    
    public Converter<Article, String> ApplicationConversionServiceFactoryBean.getArticleToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.katzan.spring.furnituretest.model.Article, java.lang.String>() {
            public String convert(Article article) {
                return new StringBuilder().append(article.getName()).append(' ').append(article.getArticleText()).toString();
            }
        };
    }
    
    public Converter<Long, Article> ApplicationConversionServiceFactoryBean.getIdToArticleConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.katzan.spring.furnituretest.model.Article>() {
            public com.katzan.spring.furnituretest.model.Article convert(java.lang.Long id) {
                return articleRepository.findOne(id);
            }
        };
    }
    
    public Converter<String, Article> ApplicationConversionServiceFactoryBean.getStringToArticleConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.katzan.spring.furnituretest.model.Article>() {
            public com.katzan.spring.furnituretest.model.Article convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Article.class);
            }
        };
    }
    
    public Converter<Big, String> ApplicationConversionServiceFactoryBean.getBigToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.katzan.spring.furnituretest.model.Big, java.lang.String>() {
            public String convert(Big big) {
                return new StringBuilder().append(big.getFile()).append(' ').append(big.getContent()).append(' ').append(big.getName()).append(' ').append(big.getFileName()).toString();
            }
        };
    }
    
    public Converter<Long, Big> ApplicationConversionServiceFactoryBean.getIdToBigConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.katzan.spring.furnituretest.model.Big>() {
            public com.katzan.spring.furnituretest.model.Big convert(java.lang.Long id) {
                return bigRepository.findOne(id);
            }
        };
    }
    
    public Converter<String, Big> ApplicationConversionServiceFactoryBean.getStringToBigConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.katzan.spring.furnituretest.model.Big>() {
            public com.katzan.spring.furnituretest.model.Big convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Big.class);
            }
        };
    }
    
    public Converter<Contact, String> ApplicationConversionServiceFactoryBean.getContactToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.katzan.spring.furnituretest.model.Contact, java.lang.String>() {
            public String convert(Contact contact) {
                return new StringBuilder().append(contact.getName()).append(' ').append(contact.getDescription()).append(' ').append(contact.getTitle()).toString();
            }
        };
    }
    
    public Converter<Long, Contact> ApplicationConversionServiceFactoryBean.getIdToContactConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.katzan.spring.furnituretest.model.Contact>() {
            public com.katzan.spring.furnituretest.model.Contact convert(java.lang.Long id) {
                return contactRepository.findOne(id);
            }
        };
    }
    
    public Converter<String, Contact> ApplicationConversionServiceFactoryBean.getStringToContactConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.katzan.spring.furnituretest.model.Contact>() {
            public com.katzan.spring.furnituretest.model.Contact convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Contact.class);
            }
        };
    }
    
    public Converter<FurnitureCategory, String> ApplicationConversionServiceFactoryBean.getFurnitureCategoryToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.katzan.spring.furnituretest.model.FurnitureCategory, java.lang.String>() {
            public String convert(FurnitureCategory furnitureCategory) {
                return new StringBuilder().append(furnitureCategory.getVirtualPath()).append(' ').append(furnitureCategory.getCategoryName()).append(' ').append(furnitureCategory.getCategoryDescription()).append(' ').append(furnitureCategory.getMetaDescription()).toString();
            }
        };
    }
    
    public Converter<Long, FurnitureCategory> ApplicationConversionServiceFactoryBean.getIdToFurnitureCategoryConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.katzan.spring.furnituretest.model.FurnitureCategory>() {
            public com.katzan.spring.furnituretest.model.FurnitureCategory convert(java.lang.Long id) {
                return furnitureCategoryRepository.findOne(id);
            }
        };
    }
    
    public Converter<String, FurnitureCategory> ApplicationConversionServiceFactoryBean.getStringToFurnitureCategoryConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.katzan.spring.furnituretest.model.FurnitureCategory>() {
            public com.katzan.spring.furnituretest.model.FurnitureCategory convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), FurnitureCategory.class);
            }
        };
    }
    
    public Converter<Long, FurnitureCollection> ApplicationConversionServiceFactoryBean.getIdToFurnitureCollectionConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.katzan.spring.furnituretest.model.FurnitureCollection>() {
            public com.katzan.spring.furnituretest.model.FurnitureCollection convert(java.lang.Long id) {
                return furnitureCollectionRepository.findOne(id);
            }
        };
    }
    
    public Converter<String, FurnitureCollection> ApplicationConversionServiceFactoryBean.getStringToFurnitureCollectionConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.katzan.spring.furnituretest.model.FurnitureCollection>() {
            public com.katzan.spring.furnituretest.model.FurnitureCollection convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), FurnitureCollection.class);
            }
        };
    }
    
    public Converter<FurnitureItem, String> ApplicationConversionServiceFactoryBean.getFurnitureItemToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.katzan.spring.furnituretest.model.FurnitureItem, java.lang.String>() {
            public String convert(FurnitureItem furnitureItem) {
                return new StringBuilder().append(furnitureItem.getServerPathString()).append(' ').append(furnitureItem.getVirtualPath()).append(' ').append(furnitureItem.getItemName()).append(' ').append(furnitureItem.getCodeNumber()).toString();
            }
        };
    }
    
    public Converter<Long, FurnitureItem> ApplicationConversionServiceFactoryBean.getIdToFurnitureItemConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.katzan.spring.furnituretest.model.FurnitureItem>() {
            public com.katzan.spring.furnituretest.model.FurnitureItem convert(java.lang.Long id) {
                return furnitureItemRepository.findOne(id);
            }
        };
    }
    
    public Converter<String, FurnitureItem> ApplicationConversionServiceFactoryBean.getStringToFurnitureItemConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.katzan.spring.furnituretest.model.FurnitureItem>() {
            public com.katzan.spring.furnituretest.model.FurnitureItem convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), FurnitureItem.class);
            }
        };
    }
    
    public Converter<FurnitureNews, String> ApplicationConversionServiceFactoryBean.getFurnitureNewsToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.katzan.spring.furnituretest.model.FurnitureNews, java.lang.String>() {
            public String convert(FurnitureNews furnitureNews) {
                return new StringBuilder().append(furnitureNews.getNewsName()).append(' ').append(furnitureNews.getNewsText()).append(' ').append(furnitureNews.getNewsTitle()).toString();
            }
        };
    }
    
    public Converter<Long, FurnitureNews> ApplicationConversionServiceFactoryBean.getIdToFurnitureNewsConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.katzan.spring.furnituretest.model.FurnitureNews>() {
            public com.katzan.spring.furnituretest.model.FurnitureNews convert(java.lang.Long id) {
                return furnitureNewsRepository.findOne(id);
            }
        };
    }
    
    public Converter<String, FurnitureNews> ApplicationConversionServiceFactoryBean.getStringToFurnitureNewsConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.katzan.spring.furnituretest.model.FurnitureNews>() {
            public com.katzan.spring.furnituretest.model.FurnitureNews convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), FurnitureNews.class);
            }
        };
    }
    
    public Converter<ImageFile, String> ApplicationConversionServiceFactoryBean.getImageFileToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.katzan.spring.furnituretest.model.ImageFile, java.lang.String>() {
            public String convert(ImageFile imageFile) {
                return new StringBuilder().append(imageFile.getFile()).append(' ').append(imageFile.getImageName()).append(' ').append(imageFile.getDescription()).append(' ').append(imageFile.getFileName()).toString();
            }
        };
    }
    
    public Converter<Long, ImageFile> ApplicationConversionServiceFactoryBean.getIdToImageFileConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.katzan.spring.furnituretest.model.ImageFile>() {
            public com.katzan.spring.furnituretest.model.ImageFile convert(java.lang.Long id) {
                return imageFileRepository.findOne(id);
            }
        };
    }
    
    public Converter<String, ImageFile> ApplicationConversionServiceFactoryBean.getStringToImageFileConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.katzan.spring.furnituretest.model.ImageFile>() {
            public com.katzan.spring.furnituretest.model.ImageFile convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), ImageFile.class);
            }
        };
    }
    
    public Converter<ServiceItem, String> ApplicationConversionServiceFactoryBean.getServiceItemToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.katzan.spring.furnituretest.model.ServiceItem, java.lang.String>() {
            public String convert(ServiceItem serviceItem) {
                return new StringBuilder().append(serviceItem.getName()).append(' ').append(serviceItem.getDescription()).append(' ').append(serviceItem.getTitle()).toString();
            }
        };
    }
    
    public Converter<Long, ServiceItem> ApplicationConversionServiceFactoryBean.getIdToServiceItemConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.katzan.spring.furnituretest.model.ServiceItem>() {
            public com.katzan.spring.furnituretest.model.ServiceItem convert(java.lang.Long id) {
                return serviceItemRepository.findOne(id);
            }
        };
    }
    
    public Converter<String, ServiceItem> ApplicationConversionServiceFactoryBean.getStringToServiceItemConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.katzan.spring.furnituretest.model.ServiceItem>() {
            public com.katzan.spring.furnituretest.model.ServiceItem convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), ServiceItem.class);
            }
        };
    }
    
    public Converter<ShopOrder, String> ApplicationConversionServiceFactoryBean.getShopOrderToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.katzan.spring.furnituretest.model.ShopOrder, java.lang.String>() {
            public String convert(ShopOrder shopOrder) {
                return new StringBuilder().append(shopOrder.getOrderDate()).append(' ').append(shopOrder.getDeliveryDate()).append(' ').append(shopOrder.getComments()).append(' ').append(shopOrder.getTotalOrderPrice()).toString();
            }
        };
    }
    
    public Converter<Long, ShopOrder> ApplicationConversionServiceFactoryBean.getIdToShopOrderConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.katzan.spring.furnituretest.model.ShopOrder>() {
            public com.katzan.spring.furnituretest.model.ShopOrder convert(java.lang.Long id) {
                return shopOrderRepository.findOne(id);
            }
        };
    }
    
    public Converter<String, ShopOrder> ApplicationConversionServiceFactoryBean.getStringToShopOrderConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.katzan.spring.furnituretest.model.ShopOrder>() {
            public com.katzan.spring.furnituretest.model.ShopOrder convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), ShopOrder.class);
            }
        };
    }
    
    public Converter<String, ShopOrderDetail> ApplicationConversionServiceFactoryBean.getStringToShopOrderDetailConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.katzan.spring.furnituretest.model.ShopOrderDetail>() {
            public com.katzan.spring.furnituretest.model.ShopOrderDetail convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), ShopOrderDetail.class);
            }
        };
    }
    
    public void ApplicationConversionServiceFactoryBean.installLabelConverters(FormatterRegistry registry) {
        registry.addConverter(getAboutUsToStringConverter());
        registry.addConverter(getIdToAboutUsConverter());
        registry.addConverter(getStringToAboutUsConverter());
        registry.addConverter(getArticleToStringConverter());
        registry.addConverter(getIdToArticleConverter());
        registry.addConverter(getStringToArticleConverter());
        registry.addConverter(getBigToStringConverter());
        registry.addConverter(getIdToBigConverter());
        registry.addConverter(getStringToBigConverter());
        registry.addConverter(getContactToStringConverter());
        registry.addConverter(getIdToContactConverter());
        registry.addConverter(getStringToContactConverter());
        registry.addConverter(getFurnitureCategoryToStringConverter());
        registry.addConverter(getIdToFurnitureCategoryConverter());
        registry.addConverter(getStringToFurnitureCategoryConverter());
        registry.addConverter(getFurnitureCollectionToStringConverter());
        registry.addConverter(getIdToFurnitureCollectionConverter());
        registry.addConverter(getStringToFurnitureCollectionConverter());
        registry.addConverter(getFurnitureItemToStringConverter());
        registry.addConverter(getIdToFurnitureItemConverter());
        registry.addConverter(getStringToFurnitureItemConverter());
        registry.addConverter(getFurnitureNewsToStringConverter());
        registry.addConverter(getIdToFurnitureNewsConverter());
        registry.addConverter(getStringToFurnitureNewsConverter());
        registry.addConverter(getImageFileToStringConverter());
        registry.addConverter(getIdToImageFileConverter());
        registry.addConverter(getStringToImageFileConverter());
        registry.addConverter(getServiceItemToStringConverter());
        registry.addConverter(getIdToServiceItemConverter());
        registry.addConverter(getStringToServiceItemConverter());
        registry.addConverter(getShopOrderToStringConverter());
        registry.addConverter(getIdToShopOrderConverter());
        registry.addConverter(getStringToShopOrderConverter());
        registry.addConverter(getShopOrderDetailToStringConverter());
        registry.addConverter(getIdToShopOrderDetailConverter());
        registry.addConverter(getStringToShopOrderDetailConverter());
        registry.addConverter(getUserAccountToStringConverter());
        registry.addConverter(getIdToUserAccountConverter());
        registry.addConverter(getStringToUserAccountConverter());
    }
    
    public void ApplicationConversionServiceFactoryBean.afterPropertiesSet() {
        super.afterPropertiesSet();
        installLabelConverters(getObject());
    }
    
}
