// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.web;

import com.katzan.spring.furnituretest.model.Big;
import com.katzan.spring.furnituretest.repository.BigRepository;
import com.katzan.spring.furnituretest.web.BigController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect BigController_Roo_Controller {
    
    @Autowired
    BigRepository BigController.bigRepository;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String BigController.create(@Valid Big big, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, big);
            return "bigs/create";
        }
        uiModel.asMap().clear();
        bigRepository.save(big);
        return "redirect:/bigs/" + encodeUrlPathSegment(big.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String BigController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Big());
        return "bigs/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String BigController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("big", bigRepository.findOne(id));
        uiModel.addAttribute("itemId", id);
        return "bigs/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String BigController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("bigs", bigRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / sizeNo, sizeNo)).getContent());
            float nrOfPages = (float) bigRepository.count() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("bigs", bigRepository.findAll());
        }
        return "bigs/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String BigController.update(@Valid Big big, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, big);
            return "bigs/update";
        }
        uiModel.asMap().clear();
        bigRepository.save(big);
        return "redirect:/bigs/" + encodeUrlPathSegment(big.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String BigController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, bigRepository.findOne(id));
        return "bigs/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String BigController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Big big = bigRepository.findOne(id);
        bigRepository.delete(big);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/bigs";
    }
    
    void BigController.populateEditForm(Model uiModel, Big big) {
        uiModel.addAttribute("big", big);
    }
    
    String BigController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
