// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.web;

import com.katzan.spring.furnituretest.model.FurnitureItem;
import com.katzan.spring.furnituretest.repository.FurnitureCategoryRepository;
import com.katzan.spring.furnituretest.repository.FurnitureCollectionRepository;
import com.katzan.spring.furnituretest.repository.FurnitureItemRepository;
import com.katzan.spring.furnituretest.repository.ImageFileRepository;
import com.katzan.spring.furnituretest.web.FurnitureItemController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect FurnitureItemController_Roo_Controller {
    
    @Autowired
    FurnitureItemRepository FurnitureItemController.furnitureItemRepository;
    
    @Autowired
    FurnitureCategoryRepository FurnitureItemController.furnitureCategoryRepository;
    
    @Autowired
    FurnitureCollectionRepository FurnitureItemController.furnitureCollectionRepository;
    
    @Autowired
    ImageFileRepository FurnitureItemController.imageFileRepository;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String FurnitureItemController.create(@Valid FurnitureItem furnitureItem, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, furnitureItem);
            return "furnitureitems/create";
        }
        uiModel.asMap().clear();
        furnitureItemRepository.save(furnitureItem);
        return "redirect:/furnitureitems/" + encodeUrlPathSegment(furnitureItem.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String FurnitureItemController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("furnitureitem", furnitureItemRepository.findOne(id));
        uiModel.addAttribute("itemId", id);
        return "furnitureitems/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String FurnitureItemController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("furnitureitems", furnitureItemRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / sizeNo, sizeNo)).getContent());
            float nrOfPages = (float) furnitureItemRepository.count() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("furnitureitems", furnitureItemRepository.findAll());
        }
        return "furnitureitems/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String FurnitureItemController.update(@Valid FurnitureItem furnitureItem, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, furnitureItem);
            return "furnitureitems/update";
        }
        uiModel.asMap().clear();
        furnitureItemRepository.save(furnitureItem);
        return "redirect:/furnitureitems/" + encodeUrlPathSegment(furnitureItem.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String FurnitureItemController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, furnitureItemRepository.findOne(id));
        return "furnitureitems/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String FurnitureItemController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        FurnitureItem furnitureItem = furnitureItemRepository.findOne(id);
        furnitureItemRepository.delete(furnitureItem);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/furnitureitems";
    }
    
    void FurnitureItemController.populateEditForm(Model uiModel, FurnitureItem furnitureItem) {
        uiModel.addAttribute("furnitureItem", furnitureItem);
        uiModel.addAttribute("furniturecategorys", furnitureCategoryRepository.findAll());
        uiModel.addAttribute("furniturecollections", furnitureCollectionRepository.findAll());
        uiModel.addAttribute("imagefiles", imageFileRepository.findAll());
    }
    
    String FurnitureItemController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
