// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.web;

import com.katzan.spring.furnituretest.model.FurnitureNews;
import com.katzan.spring.furnituretest.repository.FurnitureNewsRepository;
import com.katzan.spring.furnituretest.web.FurnitureNewsController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect FurnitureNewsController_Roo_Controller {
    
    @Autowired
    FurnitureNewsRepository FurnitureNewsController.furnitureNewsRepository;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String FurnitureNewsController.create(@Valid FurnitureNews furnitureNews, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, furnitureNews);
            return "furniturenewses/create";
        }
        uiModel.asMap().clear();
        furnitureNewsRepository.save(furnitureNews);
        return "redirect:/furniturenewses/" + encodeUrlPathSegment(furnitureNews.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String FurnitureNewsController.createForm(Model uiModel) {
        populateEditForm(uiModel, new FurnitureNews());
        return "furniturenewses/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String FurnitureNewsController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("furniturenews", furnitureNewsRepository.findOne(id));
        uiModel.addAttribute("itemId", id);
        return "furniturenewses/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String FurnitureNewsController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("furniturenewses", furnitureNewsRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / sizeNo, sizeNo)).getContent());
            float nrOfPages = (float) furnitureNewsRepository.count() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("furniturenewses", furnitureNewsRepository.findAll());
        }
        return "furniturenewses/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String FurnitureNewsController.update(@Valid FurnitureNews furnitureNews, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, furnitureNews);
            return "furniturenewses/update";
        }
        uiModel.asMap().clear();
        furnitureNewsRepository.save(furnitureNews);
        return "redirect:/furniturenewses/" + encodeUrlPathSegment(furnitureNews.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String FurnitureNewsController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, furnitureNewsRepository.findOne(id));
        return "furniturenewses/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String FurnitureNewsController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        FurnitureNews furnitureNews = furnitureNewsRepository.findOne(id);
        furnitureNewsRepository.delete(furnitureNews);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/furniturenewses";
    }
    
    void FurnitureNewsController.populateEditForm(Model uiModel, FurnitureNews furnitureNews) {
        uiModel.addAttribute("furnitureNews", furnitureNews);
    }
    
    String FurnitureNewsController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
