// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.web;

import com.katzan.spring.furnituretest.model.FurnitureCollection;
import com.katzan.spring.furnituretest.repository.FurnitureCategoryRepository;
import com.katzan.spring.furnituretest.repository.FurnitureCollectionRepository;
import com.katzan.spring.furnituretest.repository.FurnitureItemRepository;
import com.katzan.spring.furnituretest.repository.ImageFileRepository;
import com.katzan.spring.furnituretest.web.FurnitureCollectionController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect FurnitureCollectionController_Roo_Controller {
    
    @Autowired
    FurnitureCollectionRepository FurnitureCollectionController.furnitureCollectionRepository;
    
    @Autowired
    FurnitureCategoryRepository FurnitureCollectionController.furnitureCategoryRepository;
    
    @Autowired
    FurnitureItemRepository FurnitureCollectionController.furnitureItemRepository;
    
    @Autowired
    ImageFileRepository FurnitureCollectionController.imageFileRepository;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String FurnitureCollectionController.create(@Valid FurnitureCollection furnitureCollection, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, furnitureCollection);
            return "furniturecollections/create";
        }
        uiModel.asMap().clear();
        furnitureCollectionRepository.save(furnitureCollection);
        return "redirect:/furniturecollections/" + encodeUrlPathSegment(furnitureCollection.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String FurnitureCollectionController.createForm(Model uiModel) {
        populateEditForm(uiModel, new FurnitureCollection());
        return "furniturecollections/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String FurnitureCollectionController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("furniturecollection", furnitureCollectionRepository.findOne(id));
        uiModel.addAttribute("itemId", id);
        return "furniturecollections/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String FurnitureCollectionController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("furniturecollections", furnitureCollectionRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / sizeNo, sizeNo)).getContent());
            float nrOfPages = (float) furnitureCollectionRepository.count() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("furniturecollections", furnitureCollectionRepository.findAll());
        }
        return "furniturecollections/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String FurnitureCollectionController.update(@Valid FurnitureCollection furnitureCollection, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, furnitureCollection);
            return "furniturecollections/update";
        }
        uiModel.asMap().clear();
        furnitureCollectionRepository.save(furnitureCollection);
        return "redirect:/furniturecollections/" + encodeUrlPathSegment(furnitureCollection.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String FurnitureCollectionController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, furnitureCollectionRepository.findOne(id));
        return "furniturecollections/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String FurnitureCollectionController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        FurnitureCollection furnitureCollection = furnitureCollectionRepository.findOne(id);
        furnitureCollectionRepository.delete(furnitureCollection);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/furniturecollections";
    }
    
    void FurnitureCollectionController.populateEditForm(Model uiModel, FurnitureCollection furnitureCollection) {
        uiModel.addAttribute("furnitureCollection", furnitureCollection);
        uiModel.addAttribute("furniturecategorys", furnitureCategoryRepository.findAll());
        uiModel.addAttribute("furnitureitems", furnitureItemRepository.findAll());
        uiModel.addAttribute("imagefiles", imageFileRepository.findAll());
    }
    
    String FurnitureCollectionController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
