// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.web;

import com.katzan.spring.furnituretest.model.FurnitureCategory;
import com.katzan.spring.furnituretest.repository.FurnitureCategoryRepository;
import com.katzan.spring.furnituretest.repository.FurnitureCollectionRepository;
import com.katzan.spring.furnituretest.repository.FurnitureItemRepository;
import com.katzan.spring.furnituretest.repository.ImageFileRepository;
import com.katzan.spring.furnituretest.web.FurnitureCategoryController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect FurnitureCategoryController_Roo_Controller {
    
    @Autowired
    FurnitureCategoryRepository FurnitureCategoryController.furnitureCategoryRepository;
    
    @Autowired
    FurnitureCollectionRepository FurnitureCategoryController.furnitureCollectionRepository;
    
    @Autowired
    FurnitureItemRepository FurnitureCategoryController.furnitureItemRepository;
    
    @Autowired
    ImageFileRepository FurnitureCategoryController.imageFileRepository;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String FurnitureCategoryController.create(@Valid FurnitureCategory furnitureCategory, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, furnitureCategory);
            return "furniturecategorys/create";
        }
        uiModel.asMap().clear();
        furnitureCategoryRepository.save(furnitureCategory);
        return "redirect:/furniturecategorys/" + encodeUrlPathSegment(furnitureCategory.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String FurnitureCategoryController.createForm(Model uiModel) {
        populateEditForm(uiModel, new FurnitureCategory());
        return "furniturecategorys/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String FurnitureCategoryController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("furniturecategory", furnitureCategoryRepository.findOne(id));
        uiModel.addAttribute("itemId", id);
        return "furniturecategorys/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String FurnitureCategoryController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("furniturecategorys", furnitureCategoryRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / sizeNo, sizeNo)).getContent());
            float nrOfPages = (float) furnitureCategoryRepository.count() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("furniturecategorys", furnitureCategoryRepository.findAll());
        }
        return "furniturecategorys/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String FurnitureCategoryController.update(@Valid FurnitureCategory furnitureCategory, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, furnitureCategory);
            return "furniturecategorys/update";
        }
        uiModel.asMap().clear();
        furnitureCategoryRepository.save(furnitureCategory);
        return "redirect:/furniturecategorys/" + encodeUrlPathSegment(furnitureCategory.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String FurnitureCategoryController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, furnitureCategoryRepository.findOne(id));
        return "furniturecategorys/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String FurnitureCategoryController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        FurnitureCategory furnitureCategory = furnitureCategoryRepository.findOne(id);
        furnitureCategoryRepository.delete(furnitureCategory);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/furniturecategorys";
    }
    
    void FurnitureCategoryController.populateEditForm(Model uiModel, FurnitureCategory furnitureCategory) {
        uiModel.addAttribute("furnitureCategory", furnitureCategory);
        uiModel.addAttribute("furniturecollections", furnitureCollectionRepository.findAll());
        uiModel.addAttribute("furnitureitems", furnitureItemRepository.findAll());
        uiModel.addAttribute("imagefiles", imageFileRepository.findAll());
    }
    
    String FurnitureCategoryController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
