// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.web;

import com.katzan.spring.furnituretest.model.ImageFile;
import com.katzan.spring.furnituretest.repository.FurnitureCategoryRepository;
import com.katzan.spring.furnituretest.repository.FurnitureCollectionRepository;
import com.katzan.spring.furnituretest.repository.FurnitureItemRepository;
import com.katzan.spring.furnituretest.repository.ImageFileRepository;
import com.katzan.spring.furnituretest.web.ImageFileController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect ImageFileController_Roo_Controller {
    
    @Autowired
    ImageFileRepository ImageFileController.imageFileRepository;
    
    @Autowired
    FurnitureCategoryRepository ImageFileController.furnitureCategoryRepository;
    
    @Autowired
    FurnitureCollectionRepository ImageFileController.furnitureCollectionRepository;
    
    @Autowired
    FurnitureItemRepository ImageFileController.furnitureItemRepository;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ImageFileController.create(@Valid ImageFile imageFile, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, imageFile);
            return "imagefiles/create";
        }
        uiModel.asMap().clear();
        imageFileRepository.save(imageFile);
        return "redirect:/imagefiles/" + encodeUrlPathSegment(imageFile.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ImageFileController.createForm(Model uiModel) {
        populateEditForm(uiModel, new ImageFile());
        return "imagefiles/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String ImageFileController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("imagefile", imageFileRepository.findOne(id));
        uiModel.addAttribute("itemId", id);
        return "imagefiles/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String ImageFileController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("imagefiles", imageFileRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / sizeNo, sizeNo)).getContent());
            float nrOfPages = (float) imageFileRepository.count() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("imagefiles", imageFileRepository.findAll());
        }
        return "imagefiles/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ImageFileController.update(@Valid ImageFile imageFile, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, imageFile);
            return "imagefiles/update";
        }
        uiModel.asMap().clear();
        imageFileRepository.save(imageFile);
        return "redirect:/imagefiles/" + encodeUrlPathSegment(imageFile.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ImageFileController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, imageFileRepository.findOne(id));
        return "imagefiles/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ImageFileController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        ImageFile imageFile = imageFileRepository.findOne(id);
        imageFileRepository.delete(imageFile);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/imagefiles";
    }
    
    void ImageFileController.populateEditForm(Model uiModel, ImageFile imageFile) {
        uiModel.addAttribute("imageFile", imageFile);
        uiModel.addAttribute("furniturecategorys", furnitureCategoryRepository.findAll());
        uiModel.addAttribute("furniturecollections", furnitureCollectionRepository.findAll());
        uiModel.addAttribute("furnitureitems", furnitureItemRepository.findAll());
    }
    
    String ImageFileController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
