// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.web;

import com.katzan.spring.furnituretest.model.ServiceItem;
import com.katzan.spring.furnituretest.repository.ServiceItemRepository;
import com.katzan.spring.furnituretest.web.ServiceItemController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect ServiceItemController_Roo_Controller {
    
    @Autowired
    ServiceItemRepository ServiceItemController.serviceItemRepository;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String ServiceItemController.create(@Valid ServiceItem serviceItem, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, serviceItem);
            return "serviceitems/create";
        }
        uiModel.asMap().clear();
        serviceItemRepository.save(serviceItem);
        return "redirect:/serviceitems/" + encodeUrlPathSegment(serviceItem.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String ServiceItemController.createForm(Model uiModel) {
        populateEditForm(uiModel, new ServiceItem());
        return "serviceitems/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String ServiceItemController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("serviceitem", serviceItemRepository.findOne(id));
        uiModel.addAttribute("itemId", id);
        return "serviceitems/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String ServiceItemController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("serviceitems", serviceItemRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / sizeNo, sizeNo)).getContent());
            float nrOfPages = (float) serviceItemRepository.count() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("serviceitems", serviceItemRepository.findAll());
        }
        return "serviceitems/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String ServiceItemController.update(@Valid ServiceItem serviceItem, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, serviceItem);
            return "serviceitems/update";
        }
        uiModel.asMap().clear();
        serviceItemRepository.save(serviceItem);
        return "redirect:/serviceitems/" + encodeUrlPathSegment(serviceItem.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String ServiceItemController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, serviceItemRepository.findOne(id));
        return "serviceitems/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String ServiceItemController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        ServiceItem serviceItem = serviceItemRepository.findOne(id);
        serviceItemRepository.delete(serviceItem);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/serviceitems";
    }
    
    void ServiceItemController.populateEditForm(Model uiModel, ServiceItem serviceItem) {
        uiModel.addAttribute("serviceItem", serviceItem);
    }
    
    String ServiceItemController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
