// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.AboutUs;

privileged aspect AboutUs_Roo_JavaBean {
    
    public String AboutUs.getName() {
        return this.name;
    }
    
    public void AboutUs.setName(String name) {
        this.name = name;
    }
    
    public String AboutUs.getTitle() {
        return this.title;
    }
    
    public void AboutUs.setTitle(String title) {
        this.title = title;
    }
    
    public String AboutUs.getDescription() {
        return this.description;
    }
    
    public void AboutUs.setDescription(String description) {
        this.description = description;
    }
    
}
