// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.Article;

privileged aspect Article_Roo_JavaBean {
    
    public String Article.getName() {
        return this.name;
    }
    
    public void Article.setName(String name) {
        this.name = name;
    }
    
    public String Article.getArticleText() {
        return this.articleText;
    }
    
    public void Article.setArticleText(String articleText) {
        this.articleText = articleText;
    }
    
}
