// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.Big;

privileged aspect Big_Roo_JavaBean {
    
    public String Big.getContent() {
        return this.content;
    }
    
    public void Big.setContent(String content) {
        this.content = content;
    }
    
    public String Big.getName() {
        return this.name;
    }
    
    public void Big.setName(String name) {
        this.name = name;
    }
    
    public String Big.getFileName() {
        return this.fileName;
    }
    
    public void Big.setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    public long Big.getSize() {
        return this.size;
    }
    
    public void Big.setSize(long size) {
        this.size = size;
    }
    
}
