// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.Big;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Big_Roo_Jpa_Entity {
    
    declare @type: Big: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Big.id;
    
    @Version
    @Column(name = "version")
    private Integer Big.version;
    
    public Long Big.getId() {
        return this.id;
    }
    
    public void Big.setId(Long id) {
        this.id = id;
    }
    
    public Integer Big.getVersion() {
        return this.version;
    }
    
    public void Big.setVersion(Integer version) {
        this.version = version;
    }
    
}
