// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.Contact;

privileged aspect Contact_Roo_JavaBean {
    
    public String Contact.getName() {
        return this.name;
    }
    
    public void Contact.setName(String name) {
        this.name = name;
    }
    
    public String Contact.getDescription() {
        return this.description;
    }
    
    public void Contact.setDescription(String description) {
        this.description = description;
    }
    
    public String Contact.getTitle() {
        return this.title;
    }
    
    public void Contact.setTitle(String title) {
        this.title = title;
    }
    
}
