// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.FurnitureItem;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect FurnitureItem_Roo_Jpa_Entity {
    
    declare @type: FurnitureItem: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long FurnitureItem.id;
    
    @Version
    @Column(name = "version")
    private Integer FurnitureItem.version;
    
    public Long FurnitureItem.getId() {
        return this.id;
    }
    
    public void FurnitureItem.setId(Long id) {
        this.id = id;
    }
    
    public Integer FurnitureItem.getVersion() {
        return this.version;
    }
    
    public void FurnitureItem.setVersion(Integer version) {
        this.version = version;
    }
    
}
