// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.FurnitureCategory;
import com.katzan.spring.furnituretest.model.FurnitureCollection;
import com.katzan.spring.furnituretest.model.FurnitureItem;
import com.katzan.spring.furnituretest.model.ImageFile;
import java.util.Set;

privileged aspect FurnitureCategory_Roo_JavaBean {
    
    public String FurnitureCategory.getCategoryName() {
        return this.categoryName;
    }
    
    public void FurnitureCategory.setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    
    public String FurnitureCategory.getCategoryDescription() {
        return this.categoryDescription;
    }
    
    public void FurnitureCategory.setCategoryDescription(String categoryDescription) {
        this.categoryDescription = categoryDescription;
    }
    
    public String FurnitureCategory.getMetaDescription() {
        return this.metaDescription;
    }
    
    public void FurnitureCategory.setMetaDescription(String metaDescription) {
        this.metaDescription = metaDescription;
    }
    
    public String FurnitureCategory.getMetaTitle() {
        return this.metaTitle;
    }
    
    public void FurnitureCategory.setMetaTitle(String metaTitle) {
        this.metaTitle = metaTitle;
    }
    
    public String FurnitureCategory.getMetaKeywords() {
        return this.metaKeywords;
    }
    
    public void FurnitureCategory.setMetaKeywords(String metaKeywords) {
        this.metaKeywords = metaKeywords;
    }
    
    public Set<ImageFile> FurnitureCategory.getImageFiles() {
        return this.imageFiles;
    }
    
    public void FurnitureCategory.setImageFiles(Set<ImageFile> imageFiles) {
        this.imageFiles = imageFiles;
    }
    
    public Set<FurnitureCollection> FurnitureCategory.getFurnitureCollections() {
        return this.furnitureCollections;
    }
    
    public void FurnitureCategory.setFurnitureCollections(Set<FurnitureCollection> furnitureCollections) {
        this.furnitureCollections = furnitureCollections;
    }
    
    public Set<FurnitureItem> FurnitureCategory.getFurnitureItems() {
        return this.furnitureItems;
    }
    
    public void FurnitureCategory.setFurnitureItems(Set<FurnitureItem> furnitureItems) {
        this.furnitureItems = furnitureItems;
    }
    
}
