// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.FurnitureCategory;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect FurnitureCategory_Roo_Jpa_Entity {
    
    declare @type: FurnitureCategory: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long FurnitureCategory.id;
    
    @Version
    @Column(name = "version")
    private Integer FurnitureCategory.version;
    
    public Long FurnitureCategory.getId() {
        return this.id;
    }
    
    public void FurnitureCategory.setId(Long id) {
        this.id = id;
    }
    
    public Integer FurnitureCategory.getVersion() {
        return this.version;
    }
    
    public void FurnitureCategory.setVersion(Integer version) {
        this.version = version;
    }
    
}
