// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.FurnitureNews;

privileged aspect FurnitureNews_Roo_JavaBean {
    
    public String FurnitureNews.getNewsName() {
        return this.newsName;
    }
    
    public void FurnitureNews.setNewsName(String newsName) {
        this.newsName = newsName;
    }
    
    public String FurnitureNews.getNewsText() {
        return this.newsText;
    }
    
    public void FurnitureNews.setNewsText(String newsText) {
        this.newsText = newsText;
    }
    
    public String FurnitureNews.getNewsTitle() {
        return this.newsTitle;
    }
    
    public void FurnitureNews.setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle;
    }
    
}
