// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.FurnitureCategory;
import com.katzan.spring.furnituretest.model.FurnitureCollection;
import com.katzan.spring.furnituretest.model.FurnitureItem;
import com.katzan.spring.furnituretest.model.ImageFile;
import java.util.Set;
import org.springframework.web.multipart.commons.CommonsMultipartFile;

privileged aspect FurnitureCollection_Roo_JavaBean {
    
    public String FurnitureCollection.getCollectionName() {
        return this.collectionName;
    }
    
    public void FurnitureCollection.setCollectionName(String collectionName) {
        this.collectionName = collectionName;
    }
    
    public String FurnitureCollection.getCollectionDescription() {
        return this.collectionDescription;
    }
    
    public void FurnitureCollection.setCollectionDescription(String collectionDescription) {
        this.collectionDescription = collectionDescription;
    }
    
    public String FurnitureCollection.getMetaDescription() {
        return this.metaDescription;
    }
    
    public void FurnitureCollection.setMetaDescription(String metaDescription) {
        this.metaDescription = metaDescription;
    }
    
    public String FurnitureCollection.getMetaTitle() {
        return this.metaTitle;
    }
    
    public void FurnitureCollection.setMetaTitle(String metaTitle) {
        this.metaTitle = metaTitle;
    }
    
    public String FurnitureCollection.getMetaKeywords() {
        return this.metaKeywords;
    }
    
    public void FurnitureCollection.setMetaKeywords(String metaKeywords) {
        this.metaKeywords = metaKeywords;
    }
    
    public double FurnitureCollection.getCollectionPrice() {
        return this.collectionPrice;
    }
    
    public void FurnitureCollection.setCollectionPrice(double collectionPrice) {
        this.collectionPrice = collectionPrice;
    }
    
    public Boolean FurnitureCollection.getInStock() {
        return this.inStock;
    }
    
    public void FurnitureCollection.setInStock(Boolean inStock) {
        this.inStock = inStock;
    }
    
    public String FurnitureCollection.getSmallImageFile() {
        return this.smallImageFile;
    }
    
    public void FurnitureCollection.setSmallImageFile(String smallImageFile) {
        this.smallImageFile = smallImageFile;
    }
    
    public long FurnitureCollection.getSmallImageSize() {
        return this.smallImageSize;
    }
    
    public void FurnitureCollection.setSmallImageSize(long smallImageSize) {
        this.smallImageSize = smallImageSize;
    }
    
    public CommonsMultipartFile FurnitureCollection.getSmallFile() {
        return this.smallFile;
    }
    
    public String FurnitureCollection.getLargeImageFile() {
        return this.largeImageFile;
    }
    
    public void FurnitureCollection.setLargeImageFile(String largeImageFile) {
        this.largeImageFile = largeImageFile;
    }
    
    public long FurnitureCollection.getLargeImageSize() {
        return this.largeImageSize;
    }
    
    public void FurnitureCollection.setLargeImageSize(long largeImageSize) {
        this.largeImageSize = largeImageSize;
    }
    
    public CommonsMultipartFile FurnitureCollection.getLargeFile() {
        return this.largeFile;
    }
    
    public Set<ImageFile> FurnitureCollection.getImageFiles() {
        return this.imageFiles;
    }
    
    public void FurnitureCollection.setImageFiles(Set<ImageFile> imageFiles) {
        this.imageFiles = imageFiles;
    }
    
    public Set<FurnitureCategory> FurnitureCollection.getFurnitureCategories() {
        return this.furnitureCategories;
    }
    
    public void FurnitureCollection.setFurnitureCategories(Set<FurnitureCategory> furnitureCategories) {
        this.furnitureCategories = furnitureCategories;
    }
    
    public Set<FurnitureItem> FurnitureCollection.getFurnitureItems() {
        return this.furnitureItems;
    }
    
    public void FurnitureCollection.setFurnitureItems(Set<FurnitureItem> furnitureItems) {
        this.furnitureItems = furnitureItems;
    }
    
}
