// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.FurnitureCategory;
import com.katzan.spring.furnituretest.model.FurnitureCollection;
import com.katzan.spring.furnituretest.model.FurnitureItem;
import com.katzan.spring.furnituretest.model.ImageFile;
import java.util.Set;

privileged aspect ImageFile_Roo_JavaBean {
    
    public String ImageFile.getImageName() {
        return this.imageName;
    }
    
    public void ImageFile.setImageName(String imageName) {
        this.imageName = imageName;
    }
    
    public String ImageFile.getDescription() {
        return this.description;
    }
    
    public void ImageFile.setDescription(String description) {
        this.description = description;
    }
    
    public String ImageFile.getFileName() {
        return this.fileName;
    }
    
    public void ImageFile.setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    public long ImageFile.getSize() {
        return this.size;
    }
    
    public void ImageFile.setSize(long size) {
        this.size = size;
    }
    
    public Set<FurnitureCategory> ImageFile.getFurnitureCategories() {
        return this.furnitureCategories;
    }
    
    public void ImageFile.setFurnitureCategories(Set<FurnitureCategory> furnitureCategories) {
        this.furnitureCategories = furnitureCategories;
    }
    
    public Set<FurnitureCollection> ImageFile.getFurnitureCollections() {
        return this.furnitureCollections;
    }
    
    public void ImageFile.setFurnitureCollections(Set<FurnitureCollection> furnitureCollections) {
        this.furnitureCollections = furnitureCollections;
    }
    
    public Set<FurnitureItem> ImageFile.getFurnitureItems() {
        return this.furnitureItems;
    }
    
    public void ImageFile.setFurnitureItems(Set<FurnitureItem> furnitureItems) {
        this.furnitureItems = furnitureItems;
    }
    
}
