// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.ServiceItem;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect ServiceItem_Roo_Jpa_Entity {
    
    declare @type: ServiceItem: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long ServiceItem.id;
    
    @Version
    @Column(name = "version")
    private Integer ServiceItem.version;
    
    public Long ServiceItem.getId() {
        return this.id;
    }
    
    public void ServiceItem.setId(Long id) {
        this.id = id;
    }
    
    public Integer ServiceItem.getVersion() {
        return this.version;
    }
    
    public void ServiceItem.setVersion(Integer version) {
        this.version = version;
    }
    
}
