// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.ServiceItem;

privileged aspect ServiceItem_Roo_JavaBean {
    
    public String ServiceItem.getName() {
        return this.name;
    }
    
    public void ServiceItem.setName(String name) {
        this.name = name;
    }
    
    public String ServiceItem.getDescription() {
        return this.description;
    }
    
    public void ServiceItem.setDescription(String description) {
        this.description = description;
    }
    
    public String ServiceItem.getTitle() {
        return this.title;
    }
    
    public void ServiceItem.setTitle(String title) {
        this.title = title;
    }
    
}
