// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.Address;
import com.katzan.spring.furnituretest.model.ShopOrder;
import com.katzan.spring.furnituretest.model.ShopOrderDetail;
import com.katzan.spring.furnituretest.model.UserAccount;
import java.util.Date;
import java.util.List;

privileged aspect ShopOrder_Roo_JavaBean {
    
    public Address ShopOrder.getShippingAddress() {
        return this.shippingAddress;
    }
    
    public void ShopOrder.setShippingAddress(Address shippingAddress) {
        this.shippingAddress = shippingAddress;
    }
    
    public boolean ShopOrder.isBillingSameAsShipping() {
        return this.billingSameAsShipping;
    }
    
    public void ShopOrder.setBillingSameAsShipping(boolean billingSameAsShipping) {
        this.billingSameAsShipping = billingSameAsShipping;
    }
    
    public UserAccount ShopOrder.getAccount() {
        return this.account;
    }
    
    public void ShopOrder.setAccount(UserAccount account) {
        this.account = account;
    }
    
    public Date ShopOrder.getOrderDate() {
        return this.orderDate;
    }
    
    public void ShopOrder.setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    
    public Date ShopOrder.getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void ShopOrder.setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    
    public String ShopOrder.getComments() {
        return this.comments;
    }
    
    public void ShopOrder.setComments(String comments) {
        this.comments = comments;
    }
    
    public Double ShopOrder.getTotalOrderPrice() {
        return this.totalOrderPrice;
    }
    
    public void ShopOrder.setTotalOrderPrice(Double totalOrderPrice) {
        this.totalOrderPrice = totalOrderPrice;
    }
    
    public List<ShopOrderDetail> ShopOrder.getOrderDetails() {
        return this.orderDetails;
    }
    
}
