// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.FurnitureItem;
import com.katzan.spring.furnituretest.model.ShopOrderDetail;

privileged aspect ShopOrderDetail_Roo_JavaBean {
    
    public FurnitureItem ShopOrderDetail.getFurnitureItem() {
        return this.furnitureItem;
    }
    
    public void ShopOrderDetail.setFurnitureItem(FurnitureItem furnitureItem) {
        this.furnitureItem = furnitureItem;
    }
    
    public Integer ShopOrderDetail.getQuantity() {
        return this.quantity;
    }
    
    public void ShopOrderDetail.setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    
}
