// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.ShopOrderDetail;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect ShopOrderDetail_Roo_Jpa_Entity {
    
    declare @type: ShopOrderDetail: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long ShopOrderDetail.id;
    
    @Version
    @Column(name = "version")
    private Integer ShopOrderDetail.version;
    
    public ShopOrderDetail.new() {
        super();
    }

    public Long ShopOrderDetail.getId() {
        return this.id;
    }
    
    public void ShopOrderDetail.setId(Long id) {
        this.id = id;
    }
    
    public Integer ShopOrderDetail.getVersion() {
        return this.version;
    }
    
    public void ShopOrderDetail.setVersion(Integer version) {
        this.version = version;
    }
    
}
