// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furnituretest.model;

import com.katzan.spring.furnituretest.model.Address;
import com.katzan.spring.furnituretest.model.UserAccount;
import java.util.Date;

privileged aspect UserAccount_Roo_JavaBean {
    
    public String UserAccount.getFirstName() {
        return this.firstName;
    }
    
    public void UserAccount.setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    public String UserAccount.getLastName() {
        return this.lastName;
    }
    
    public void UserAccount.setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    public Date UserAccount.getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void UserAccount.setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    
    public Address UserAccount.getAddress() {
        return this.address;
    }
    
    public void UserAccount.setAddress(Address address) {
        this.address = address;
    }
    
    public String UserAccount.getEmailAddress() {
        return this.emailAddress;
    }
    
    public void UserAccount.setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    
    public String UserAccount.getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void UserAccount.setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    
    public String UserAccount.getUsername() {
        return this.username;
    }
    
    public void UserAccount.setUsername(String username) {
        this.username = username;
    }
    
    public String UserAccount.getPassword() {
        return this.password;
    }
    
    public void UserAccount.setPassword(String password) {
        this.password = password;
    }
    
}
